export const CHANGE_DEFAULT_BACKGROUND_COLOR = 'CHANGE_DEFAULT_BACKGROUND_COLOR';
export const CHANGE_DEFAULT_CARD_COLOR = 'CHANGE_DEFAULT_CARD_COLOR';
export const SET_STICKY_NOTES = 'SET_STICKY_NOTES';
export const ADD_STICKY_NOTE = 'ADD_STICKY_NOTE';
export const UPDATE_STICKY_NOTE = 'UPDATE_STICKY_NOTE';
export const DELETE_STICKY_NOTE = 'DELETE_STICKY_NOTE';
